name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --disable=C0303,C0301,C0116,C0103,W1203,W0718,W1203,C0411,W0611,W0612,R0914,R0904,W0613,W0612,C0207,W1514,W0212,W0612,C0121,C0413,E0401,R0915,R0912,C0415,W1309,R1710,R0915,R0912,W1309,R1702,C0201,C0415,C0115, $(git ls-files '*.py')
